version: '3'
services:
  accenture:
    build: .
    ports:
      - 3333:3333
    environment:
      APP_PORT: 3333
      DB_HOST: mongodb
      JWT_KEY: I1NiIsInR5cCI6IkpXVCJ9
      JWT_EXPIRESIN: 31m 

    depends_on: 
      - mongodb
    links: 
       - mongodb  

  mongodb:
    image: mongo
    ports:
      - 27017:27017